import { useNextSanityImage } from 'next-sanity-image'
import Head from 'next/head'
import Link from "next/link"
import router from 'next/router'
import Section from '../components/Section'
import WineCard from '../components/WineCard'
import {sanityClient, urlFor} from "../lib/sanity"

const recipesQuery = `*[_type=="product"]{
  _id,
  name,
  slug,
  productImage,
  factory,
  price
}`

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Umeshu Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Section 
      imgUrl={"/hero1.jpg"}
      heading="起源"
      content="在奈良公園的東南方，有一個名為“清水町”的區域，是著名的水源地。
      在江戶時代之前，該地區有幾家釀酒廠生產奈良清酒。
      到了明治 10 年，“八木酒造”繼承了其中一家酒造酒廠，並延續了這一傳統。
      我們與第五任社長八木武樹進行了交談。"
      />
      <Section
      imgUrl={"/hero2.jpg"}
      heading="來自山上的福水"
      content="在世界遺產“春日山森林”腳下的八木酒造。
      據說，作為春日大社的神山長期受到保護的原始森林的福水，流淌在該地區的地下。
      八木造酒廠至今仍從釀酒廠的深井中抽取地下水，用於釀造清酒。"
      />
      <Section
      imgUrl={"/hero3.jpg"}
      heading="將奈良釀造酒的傳統傳承至今"
      content="在室町時代，奈良酒作為“南東諸白（用白米釀造的優質奈良酒）”而廣受歡迎。
      另外，在升力寺建造的“寶大仙”也很有名，據說在諸白製作之前就已經確立了製壺的技術
      1999年，酒母“菩提庫”在清酒的發源地升力寺成功復活，八木酒造每年都用這位酒母釀造清酒。"
      />
      <Section
      imgUrl={"/hero4.jpg"}
      heading="令人著迷的歷史悠久產品"
      content="  在老字號的古色古香的商店裡，排列著各種各樣的產品，例如“Masuhei”、燒酒和利口酒等。
        以花札為主題的複古可愛標籤的“月瀨梅原酒”等梅酒種類繁多，在店內品嚐時，可以感受到時光倒流般的懷舊氛圍。
        此外，這款月瀨梅原清酒口味成熟，在2015年全國梅酒博覽會上獲得金獎。"
      extraImage={"/hero5.jpg"}
      />
      <div className="shop">
        <div className="shop_info">
          <div className="shop_image">
            <img
            src={"/shopphoto.jpg"}           
            />
          </div>
          <div className="shop_address">
            <h5>八木酒造</h5>
            <p>地址　奈良市高畑町915番地</p>
            <p>時間　9:00-17:00</p>
            <p>完全予約制（1回20人まで）、無料。ご希望の方は、事前にお電話でお申込みください。</p>
            <p>0742-26-2300</p>
          </div>
        </div>

      </div>
      <div className="footer">
        <Link href="/product" className="shop_button_link">
          <button className="shop_button">瀏覽商品</button>
        </Link>
      </div>
    </div>
  )
}

export async function getStaticProps(){
  const data = await sanityClient.fetch(recipesQuery)

  return {
    props:{ data }
  }
}